# Travis CI будет использовать язык java.
language: java
install: true

# Версия JDK для сборки проекта
jdk: oraclejdk11

services:
  - postgresql

os:
  - linux

dist: xenial

before_install:
  - psql -c 'create database todolist;' -U postgres

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# И отправлять на сервис https://codecov.io/
after_success: bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="fa691241-9938-4bd1-9d87-b28bf147e582"
